language: java
jdk:
- openjdk8
dist: bionic
before_install:
- openssl aes-256-cbc -K $encrypted_8f2a81d544cc_key -iv $encrypted_8f2a81d544cc_iv -in travis/pubring.gpg.enc -out travis/pubring.gpg -d
- openssl aes-256-cbc -K $encrypted_5c292d804727_key -iv $encrypted_5c292d804727_iv -in travis/secring.gpg.enc -out travis/secring.gpg -d
script:
- mvn verify
after_success:
- mvn coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis/settings.xml -DskipTests=true -Possrh -Prelease
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^bullet-pulsar-[0-9]+\\.[0-9]+\\.[0-9]+/"
env:
  global:
  - GPG_EXECUTABLE=gpg
  - secure: qe3optdnnIrKF6Ts/o0sP5ZscJw7hbYjQQsr5t8/sbmax9Z9T46+6RpUEjC/GzySbe7iXqy0NZaC2PNnbiHfFtnvs1ok2+qYYcbDY1SEDKGIDSnjrYn5napen+yHZBzJFvG1f4LTZrSvhkiGTETyICXmoGqxmWrF+U1tOqF0yBWD44asG6w4mrADetbxOV5+yf923E8VVYyj3Kz4b/mmfJoetZGvibN0euKbDfQUS60YiQuPViUwpK2symWAg41d10DJ4BF0XO7H2eDWfLazdXlA+RLcbOsaANynOUnXn0FLILGyelZusQYH5kahzdJ0/wyiKjlYtE8gpm52irc/pKKIR9l5IA7+j2Gm/XoAp0tMWPdull03cnGwci7KrYSpd7b6aQ/xg+2FqVG9PT7BpqCy6iOIVCzfgjqY7GgNsSOOZfZ1lszgcS8/Tf7WAJPQEXJv1QY8Qi5UdiwVD0L9YJtUSujCgTj2jwoflfyy2QNHkvbRwJXf6wQ9hyL6xY1IqOrCDEKASegQEXcdz+erMu1kyVRk03yJMiJKM8ea66PXge2wXobm6gsakTA4Byc8qDoB4XRLTJisiAWSAurNeuOOvWzBgctpT2arVL7jwV7NV1lsE2Ce6ZXSqYo6jb7r+76PPD32mjf4kU4TlmNdrUUvCtdietmiLhSlzus+eOI=
  - secure: hAtR2763Wnm1bS5ZRd/usAl2hopAU+mQ4i/DASj9EoLlwlNLizH072XbbRKDnHWoUl86igAtMGg2XneteRZcIS7DLtf+h5OW3sOiNZUk7uTehYQwW2yKNdDIMrPU0BTxkzjsvoUwPVKtCVd4tYW/C3o1ezQ66M72aoticzdh9qwcoP0thrD3H2t5cjYqT2dQzmngW2yJAn64L9qkH5sYZMAbuKhxRWc/AswZUpyjbPb4YkT8n59v13r5byWwYwwDqe0JSLOk0bldjN3gE/c/KeW+Gx742UQIk1KlDhpEMchvYjzeDWZou9J7/2TNST2gRFLcVRy2qfMfKfK6woB3XnTamQyB/fQzEJam9okc/JsaDhpSepjS4UyB3TB/yQ4Q0dwZ8Mj9UT2IUVm/032Cermguxl+s5BNn1pO1oOgC/ZteTE9CeDQHII1kIyPwA/2R9y6SkS8E+EdDtIfUYJyp4q52Su1i/p8peCsrGgsrVigpRJrKbnQHGdf8qywbABrjrsgg/3L2c8rZ3EmzxRH1b2PTjEZqtumEhl36hiT1QGd0H3UKgu0uYE6vNRt9AKO4TXnoqGvpwpbUTcl/glq2gboTW9p4sKZDn02H6Uu+/Jf/g2ZzsgAx1Fy+g2nbi+3x+MFYt6z5xO1CktV1c81sPpQQXxhcUrHdVHbw31fCVo=
  - secure: WknI1dpEL1MzIDBVIfeUBdLcF9qlemGVaVAnwWfmWLW6guypxc4MB6k9P9M6ldaN6Mzfwa2345wBTUrwwGGbrXLPAQ6H4tp6BYekxVLlAAqsYvyqE8P4MUryXs/qVLxWAGhoswEK+Tq2IYAjH2FjtphiX0Y58rv9Kghwsb+K3VVNRt6nM7sLN3APTweAw7XZnaFMDEd/1nStFjeVdM7bybyZL/y+vN7/jdpenvLFPkoOnWmiwqmLljRmx0aL1bPrSALDTNn+HukUinOmWlJbjA4GE8dGV+cuufTY629hD/IFpZA0TIz7QyA4eqW7HS2r8LDUTN+9efH4H46HRdHcKSXrs4WfWUa6yYDGgF+MHp0ILHzq/NZCT74DyJcFwuZozA0Gvhf8PkHOQTa2cFcYP5Sl5U0tDvf0O1lScTs/Y8VhxmdxFhFxy2kz7mRjSfSUiAawOOvJ+qqtYZmKVxxqUcd94PmfKAahA30DjNhbVcekldVLijrwBUP2IAhd6kduLHPBmreL9SXRDBHBTmsHJyGxMU6jtRm0MufNv15Yb1OsuDjFTOiVT4qT5nmTF0hmH3kKcbwEJBeyyHwsyiQD6tBY4QR6hvxyWA+5MZ7HQRVkte6dHs+M1JoYrJmEuL/VxPn02a2EbHLIycAnB6HQqXH/PYEi/I52RXb3yD+C924=
